# Generated by Django 5.1.7 on 2025-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='colorazioni',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='misure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
