# Generated by Django 5.1.7 on 2025-04-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prodotto_colorazioni_prodotto_misure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='colorazioni',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='misure',
        ),
        migrations.AddField(
            model_name='categoria',
            name='immagine',
            field=models.ImageField(default=None, upload_to='categorie/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='disponibilita',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='OggettoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrello')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prodotto')),
            ],
            options={
                'unique_together': {('carrello', 'prodotto')},
            },
        ),
    ]
