# Generated by Django 5.1.7 on 2025-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrello_remove_prodotto_colorazioni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='categorie/'),
        ),
    ]
