# Generated by Django 5.1.7 on 2025-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_immagine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OggettoCarrello',
            new_name='CarrelloItem',
        ),
        migrations.RenameField(
            model_name='carrello',
            old_name='data_creazione',
            new_name='creato_il',
        ),
        migrations.AlterUniqueTogether(
            name='carrelloitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carrello',
            name='session_id',
        ),
        migrations.AddField(
            model_name='carrello',
            name='sessione',
            field=models.CharField(default='default_sessione', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
