# Generated by Django 5.1.7 on 2025-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_banner_ordine_ordineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='altezza',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='banner',
            name='larghezza',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
