# Generated by Django 5.1.7 on 2025-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner_altezza_banner_larghezza_prodotto_altezza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmaginePersonalizzata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('immagine', models.ImageField(upload_to='immagini_personalizzate/')),
                ('altezza', models.PositiveIntegerField(default=400)),
                ('larghezza', models.PositiveIntegerField(default=600)),
                ('attivo', models.BooleanField(default=True)),
            ],
        ),
    ]
