# Generated by Django 5.1.7 on 2025-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_immaginepersonalizzata'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='colorazioni',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
