# Generated by Django 5.1.7 on 2025-04-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prodotto_colorazioni'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='banners/')),
                ('titolo', models.CharField(max_length=150)),
                ('sottotitolo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('immagine', models.ImageField(help_text='Puoi caricare anche immagini già presenti in static/images se le inserisci manualmente', upload_to='homecards/')),
                ('link_custom', models.URLField(blank=True, null=True)),
                ('categoria_collegata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('prodotto_collegato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prodotto')),
            ],
        ),
    ]
