# Generated by Django 5.1.7 on 2025-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homebanner_homecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='altezza',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='larghezza',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='homecard',
            name='altezza',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='homecard',
            name='larghezza',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
