# Generated by Django 5.1.7 on 2025-04-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homebanner_altezza_homebanner_larghezza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='altezza',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='larghezza',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
