# Generated by Django 5.1.7 on 2025-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categoria_altezza_categoria_descrizione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='cap',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='cap_fatt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='citta',
            field=models.CharField(default='sconosciuta ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='citta_fatt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='cognome',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='cognome_fatt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='fatturazione_diversa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordine',
            name='indirizzo',
            field=models.CharField(default='sconosciuto', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='indirizzo_fatt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='nome',
            field=models.CharField(default='sconosciuto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='nome_fatt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='provincia',
            field=models.CharField(default='sconosciuto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='provincia_fatt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
