# Generated by Django 5.1.7 on 2025-04-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ordine_cap_ordine_cap_fatt_ordine_citta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='civico',
            field=models.CharField(default='sconosciuto', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='civico_fatt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
