# Generated by Django 5.1.7 on 2025-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ordine_civico_ordine_civico_fatt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='altezza',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='larghezza',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='sottotitolo',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homebanner/videos/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='homebanner/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='titolo',
            field=models.CharField(max_length=100),
        ),
    ]
