# Generated by Django 5.1.7 on 2025-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_homebanner_altezza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='altezza',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='larghezza',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
