# Generated by Django 5.1.7 on 2025-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homebanner_altezza_homebanner_larghezza'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banner', 'Banner'), ('card', 'Card'), ('testo', 'Area Testo')], max_length=20)),
                ('zona', models.CharField(choices=[('hero', 'In Alto'), ('center', 'Al Centro'), ('bottom', 'In Fondo'), ('custom', 'Sezione Personalizzata')], default='center', max_length=20)),
                ('titolo', models.CharField(blank=True, max_length=200, null=True)),
                ('contenuto', models.TextField(blank=True, null=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='home_elementi/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home_elementi/video/')),
                ('larghezza', models.PositiveIntegerField(blank=True, null=True)),
                ('altezza', models.PositiveIntegerField(blank=True, null=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('visibile', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='altezza',
            field=models.PositiveIntegerField(blank=True, help_text='Inserisci l’altezza in pixel (es. 500)', null=True, verbose_name='Altezza (px)'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='larghezza',
            field=models.PositiveIntegerField(blank=True, help_text='Inserisci la larghezza in pixel (es. 900)', null=True, verbose_name='Larghezza (px)'),
        ),
    ]
