# Generated by Django 5.1.7 on 2025-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homeelemento_alter_homebanner_altezza_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeelemento',
            options={'ordering': ['zona', 'ordine']},
        ),
        migrations.RenameField(
            model_name='homeelemento',
            old_name='contenuto',
            new_name='contenuto_testo',
        ),
        migrations.RemoveField(
            model_name='homeelemento',
            name='visibile',
        ),
        migrations.AlterField(
            model_name='homeelemento',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='elementi/'),
        ),
        migrations.AlterField(
            model_name='homeelemento',
            name='tipo',
            field=models.CharField(choices=[('testo', 'Testo'), ('immagine', 'Immagine'), ('video', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='homeelemento',
            name='titolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeelemento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='elementi/'),
        ),
        migrations.AlterField(
            model_name='homeelemento',
            name='zona',
            field=models.CharField(choices=[('hero', 'Hero'), ('center', 'Centro'), ('bottom', 'Fondo'), ('custom', 'Custom')], default='center', max_length=20),
        ),
    ]
