# Generated by Django 5.1.7 on 2025-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_homeelemento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSalvato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Home Layout', max_length=100)),
                ('dati_json', models.TextField()),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
