# Generated by Django 5.1.7 on 2025-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_layoutsalvato'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=300)),
                ('height', models.FloatField(default=150)),
                ('ordine', models.IntegerField(default=0)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='layoutsalvato',
            old_name='dati_json',
            new_name='contenuto',
        ),
        migrations.RenameField(
            model_name='layoutsalvato',
            old_name='aggiornato_il',
            new_name='salvato_il',
        ),
        migrations.RemoveField(
            model_name='layoutsalvato',
            name='nome',
        ),
    ]
