# Generated by Django 5.1.7 on 2025-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_layoutelemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto_html', models.TextField()),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
