# Generated by Django 5.1.7 on 2025-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_layouthome'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='posizione',
            field=models.CharField(choices=[('hero', 'Hero Zone (in alto)'), ('center', 'Center Zone (centrale)'), ('bottom', 'Bottom Zone (in basso)')], default='hero', max_length=10),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='altezza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='larghezza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
