# Generated by Django 5.1.7 on 2025-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_homebanner_posizione_alter_homebanner_altezza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='New Collections', max_length=200)),
                ('sottotitolo', models.TextField(blank=True, null=True)),
                ('classe_titolo', models.CharField(blank=True, help_text='Esempio: fw-bold fs-1 text-primary', max_length=100, null=True)),
                ('classe_sottotitolo', models.CharField(blank=True, help_text='Esempio: text-muted fs-6', max_length=100, null=True)),
                ('testo_extra', models.TextField(blank=True, null=True)),
                ('font_family', models.CharField(blank=True, help_text="Esempio: 'Playfair Display', cursive", max_length=100, null=True)),
            ],
        ),
    ]
