# Generated by Django 5.1.7 on 2025-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cardsezione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='KAIRA', max_length=100)),
                ('descrizione', models.TextField(default='Scopri il nostro store di moda. Qualità, stile e convenienza in un unico posto.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('colore_testo', models.CharField(default='#000000', help_text='Es: #000000 per nero', max_length=7)),
                ('font_brand', models.CharField(default='Arial', help_text='Es: Arial, Roboto, ecc.', max_length=100)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
