# Generated by Django 5.1.7 on 2025-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessaggioContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('oggetto', models.CharField(max_length=150)),
                ('messaggio', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('letto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaginaInformativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('chi_siamo', 'Chi siamo'), ('sostenibilita', 'Sostenibilità')], max_length=30, unique=True)),
                ('documento', models.FileField(upload_to='documenti_informativi/')),
            ],
        ),
    ]
