# Generated by Django 5.1.7 on 2025-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_messaggiocontatto_paginainformativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('chi-siamo', 'Chi Siamo'), ('sostenibilita', 'Sostenibilità')], unique=True)),
                ('titolo', models.CharField(max_length=100)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='informative/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='informative/')),
                ('contenuto', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaginaInformativa',
        ),
    ]
