# Generated by Django 5.1.7 on 2025-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_informativa_delete_paginainformativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='tiktok',
            new_name='twitter',
        ),
        migrations.AddField(
            model_name='brand',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='colore_testo',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='font_brand',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
