# Generated by Django 5.1.7 on 2025-04-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_tiktok_brand_twitter_brand_youtube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SottoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='sottocategorie/')),
                ('larghezza', models.PositiveIntegerField(default=300)),
                ('altezza', models.PositiveIntegerField(default=200)),
                ('descrizione', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sottocategorie', to='core.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sottocategoria'),
        ),
    ]
