# Generated by Django 5.1.7 on 2025-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sottocategoria_prodotto_sottocategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaggiocontatto',
            name='letto',
        ),
        migrations.AlterField(
            model_name='messaggiocontatto',
            name='oggetto',
            field=models.CharField(max_length=200),
        ),
    ]
