# Generated by Django 5.1.7 on 2025-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_messaggiocontatto_letto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggiocontatto',
            name='letto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messaggiocontatto',
            name='oggetto',
            field=models.CharField(max_length=255),
        ),
    ]
