# Generated by Django 5.1.7 on 2025-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_messaggiocontatto_letto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggiocontatto',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='allegati/'),
        ),
    ]
