# Generated by Django 5.1.7 on 2025-04-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_messaggiocontatto_allegato'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codice',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='codice_magazzino',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='codice_prodotto',
            field=models.CharField(default='prodotto_default', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='codice',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('sottocategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sottocategoria')),
            ],
        ),
    ]
