# Generated by Django 5.1.7 on 2025-04-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_categoria_codice_prodotto_codice_magazzino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrezzoSpedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
            ],
        ),
    ]
