# Generated by Django 5.1.7 on 2025-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_prezzospedizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInformativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenuto_testo', models.TextField(blank=True, null=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='pagine/')),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
