# Generated by Django 5.1.7 on 2025-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_paginainformativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainformativa',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pagine/pdf/'),
        ),
    ]
