# Generated by Django 5.1.7 on 2025-04-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_paginainformativa_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainformativa',
            name='mostra_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
