# Generated by Django 5.1.7 on 2025-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_paginainformativa_mostra_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContattiBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Kaira Shop', max_length=100)),
                ('indirizzo', models.CharField(default='Via Nettunia 77', max_length=200)),
                ('cap_citta', models.CharField(default='84045 Altavilla Silentina, SA', max_length=100)),
                ('email', models.EmailField(default='info@kaira.it', max_length=254)),
                ('telefono', models.CharField(default='+39 320 000 0000', max_length=20)),
            ],
        ),
    ]
