# Generated by Django 5.1.7 on 2025-04-18 14:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_contattibrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainformativa',
            name='contenuto_testo',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Testo'),
            preserve_default=False,
        ),
    ]
