# Generated by Django 5.1.7 on 2025-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_paginainformativa_contenuto_testo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainformativa',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pagine/video/'),
        ),
    ]
