# Generated by Django 5.1.7 on 2025-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_paginainformativa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='codice_magazzino',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
