# Generated by Django 5.1.7 on 2025-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_ordine_codice_ordine_alter_ordine_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='codice_fiscale',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
