# Generated by Django 5.1.7 on 2025-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_ordine_codice_fiscale_ordine_email_ordine_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contattibrand',
            name='partita_iva',
            field=models.CharField(default='0001587963', max_length=100),
        ),
    ]
