# Generated by Django 5.1.7 on 2025-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_contattibrand_partita_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AddField(
            model_name='contattibrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pagine/'),
        ),
    ]
