# Generated by Django 5.1.7 on 2025-04-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_brand_logo_contattibrand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='link',
            field=models.URLField(blank=True, help_text='Link ufficiale del brand (opzionale)', null=True),
        ),
    ]
