# Generated by Django 5.1.7 on 2025-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_brand_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='attivo',
            field=models.BooleanField(default=True, help_text='Se selezionato, il brand sarà visibile nel sito.'),
        ),
    ]
