# Generated by Django 5.2 on 2025-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_brand_attivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_1',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_2',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_testo',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_video_1',
            field=models.PositiveIntegerField(blank=True, default=360, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_video_2',
            field=models.PositiveIntegerField(blank=True, default=360, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='documento_1',
            field=models.FileField(blank=True, null=True, upload_to='documenti_prodotti/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_1',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_2',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_1',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_2',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_testo',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_video_1',
            field=models.PositiveIntegerField(blank=True, default=640, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_video_2',
            field=models.PositiveIntegerField(blank=True, default=640, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='testo_aggiuntivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='video_prodotti/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='video_prodotti/'),
        ),
    ]
