# Generated by Django 5.2 on 2025-04-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_prodotto_altezza_extra_1_prodotto_altezza_extra_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenutoMultimediale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='prodotti_extra/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_prodotti/')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documenti_prodotti/')),
                ('testo', models.TextField(blank=True, null=True)),
                ('altezza', models.PositiveIntegerField(blank=True, default=300, null=True)),
                ('larghezza', models.PositiveIntegerField(blank=True, default=300, null=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenuti', to='core.prodotto')),
            ],
        ),
    ]
