# Generated by Django 5.2 on 2025-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_contenutomultimediale'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_3',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_4',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_5',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_6',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_7',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_extra_8',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_3',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_4',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_5',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_6',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_7',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine_extra_8',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti_extra/'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_3',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_4',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_5',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_6',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_7',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_extra_8',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
    ]
