# Generated by Django 5.2 on 2025-04-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_prodotto_altezza_extra_3_prodotto_altezza_extra_4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenutoMultimediale',
        ),
    ]
