# Generated by Django 5.2 on 2025-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_delete_contenutomultimediale'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_1',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_2',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_3',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_4',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_5',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_6',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_7',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='altezza_descrizione_8',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_1',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_2',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_3',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_4',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_5',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_6',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_7',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='larghezza_descrizione_8',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='misura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='taglia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
