# Generated by Django 5.2 on 2025-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_prodotto_altezza_descrizione_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='colorazioni',
            field=models.CharField(blank=True, help_text='Inserisci i codici colore HEX separati da virgola, es. #FF0000,#00FF00', max_length=255),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='misura',
            field=models.CharField(blank=True, choices=[('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='taglia',
            field=models.CharField(blank=True, choices=[('XS', 'XS (34 EU)'), ('S', 'S (36 EU)'), ('M', 'M (38 EU)'), ('L', 'L (40 EU)'), ('XL', 'XL (42 EU)'), ('XXL', 'XXL (44 EU)'), ('XXXL', 'XXXL (46 EU)')], max_length=5, null=True),
        ),
    ]
