# Generated by Django 5.2 on 2025-04-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_prodotto_colorazioni_alter_prodotto_misura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='misura',
            field=models.CharField(blank=True, choices=[('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60')], max_length=5, null=True),
        ),
    ]
