# Generated by Django 5.2 on 2025-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_cookieconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prezzospedizione',
            name='prezzo',
        ),
        migrations.AddField(
            model_name='prezzospedizione',
            name='percentuale_sconto',
            field=models.PositiveIntegerField(default=0, help_text='Percentuale di sconto da applicare al totale (es. 10 per 10%).'),
        ),
        migrations.AddField(
            model_name='prezzospedizione',
            name='prezzo_spedizione',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo della spedizione da aggiungere al totale (può essere nullo).', max_digits=7, null=True),
        ),
    ]
