# Generated by Django 5.2 on 2025-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_prezzospedizione_prezzo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prezzospedizione',
            name='percentuale_sconto',
        ),
        migrations.RemoveField(
            model_name='prezzospedizione',
            name='prezzo_spedizione',
        ),
        migrations.AddField(
            model_name='prezzospedizione',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
