# Generated by Django 5.2 on 2025-04-25 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_prezzospedizione_percentuale_sconto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodiceSconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('percentuale', models.PositiveIntegerField(help_text='Percentuale di sconto (es. 10 per 10%)')),
                ('usato', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
