# Generated by Django 5.1.7 on 2025-04-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_codicesconto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codicesconto',
            old_name='creato_il',
            new_name='data_creazione',
        ),
        migrations.AddField(
            model_name='codicesconto',
            name='multiuso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codicesconto',
            name='codice',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codicesconto',
            name='percentuale',
            field=models.PositiveIntegerField(),
        ),
    ]
