# Generated by Django 5.1.7 on 2025-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_rename_creato_il_codicesconto_data_creazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codicesconto',
            name='codice',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
