# Generated by Django 5.1.7 on 2025-04-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_codicesconto_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='pagato',
            field=models.BooleanField(default=False),
        ),
    ]
