# Generated by Django 5.2 on 2025-04-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_ordine_pagato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codicesconto',
            name='sconto_globale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordine',
            name='codice_sconto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='sconto_percentuale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codicesconto',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
