# Generated by Django 5.2 on 2025-04-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_codicesconto_sconto_globale_ordine_codice_sconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrello',
            name='codice_sconto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.codicesconto'),
        ),
        migrations.AddField(
            model_name='carrello',
            name='prezzo_spedizione',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
