# Generated by Django 5.2 on 2025-04-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_carrello_codice_sconto_carrello_prezzo_spedizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='prezzo_spedizione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prezzospedizione'),
        ),
        migrations.AddField(
            model_name='prezzospedizione',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prezzospedizione',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
