# Generated by Django 5.2 on 2025-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_ordine_prezzo_spedizione_prezzospedizione_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrello',
            name='prezzo_spedizione',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
