# Generated by Django 5.2 on 2025-05-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_interactionlog_http_method_interactionlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='email_inviata',
            field=models.BooleanField(default=False),
        ),
    ]
