# Generated by Django 5.2 on 2025-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_ordine_email_inviata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrisciaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='', max_length=100, verbose_name='Titolo')),
                ('testo', models.CharField(max_length=255, verbose_name='Testo da mostrare')),
                ('attiva', models.BooleanField(default=False, verbose_name='Attiva')),
                ('luogo', models.CharField(choices=[('footer', 'Footer'), ('navbar', 'Navbar')], default='footer', max_length=20, verbose_name='Dove mostrare')),
                ('colore_sfondo', models.CharField(default='#0d6efd', max_length=7, verbose_name='Colore di sfondo (es: #0d6efd)')),
                ('colore_testo', models.CharField(default='#ffffff', max_length=7, verbose_name='Colore del testo (es: #ffffff)')),
                ('velocita', models.PositiveIntegerField(default=20, help_text='Valore in secondi. Più basso = più veloce', verbose_name='Velocità (secondi per ciclo)')),
            ],
        ),
    ]
