# Generated by Django 5.2 on 2025-05-07 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_strisciainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazzino',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='magazzino',
            name='sottocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sottocategoria'),
        ),
    ]
