# Generated by Django 5.2 on 2025-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_magazzino_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
