# Generated by Django 5.2 on 2025-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ordine_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='titolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
