# Generated by Django 5.2 on 2025-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_homebanner_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sottocategoria',
            name='contenuto_altezza',
            field=models.PositiveIntegerField(default=300, verbose_name='Altezza contenuto (px)'),
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='contenuto_html',
            field=models.TextField(blank=True, verbose_name='Contenuto personalizzato'),
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='contenuto_larghezza',
            field=models.PositiveIntegerField(default=800, verbose_name='Larghezza contenuto (px)'),
        ),
    ]
