# Generated by Django 5.2 on 2025-05-12 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_sottocategoria_contenuto_altezza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codicesconto',
            name='data_creazione',
        ),
        migrations.RemoveField(
            model_name='codicesconto',
            name='sconto_globale',
        ),
        migrations.AddField(
            model_name='categoria',
            name='is_sconto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='percentuale_sconto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codicesconto',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codicesconto',
            name='scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='colore_bottone',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='font_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='font_titolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='immagine_sfondo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='sottotitolo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='testo_bottone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='visibile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='carrello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrello'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='totale_pagare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordineitem',
            name='data_acquisto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordineitem',
            name='pagato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordineitem',
            name='prezzo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='is_sconto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='percentuale_sconto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='is_sconto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='percentuale_sconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='codicesconto',
            name='codice',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codicesconto',
            name='percentuale',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prezzospedizione',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
