# Generated by Django 5.2 on 2025-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_codicesconto_data_creazione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='carrello',
        ),
        migrations.AddField(
            model_name='ordine',
            name='carrello_sessione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
