# Generated by Django 5.2 on 2025-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_ordine_carrello_ordine_carrello_sessione'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrello',
            name='totale_carrello',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
