# Generated by Django 5.2 on 2025-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_carrello_totale_carrello'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrello',
            name='carrello_sconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrello',
            name='carrello_spese_spedizione',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
