# Generated by Django 5.2 on 2025-05-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_carrello_carrello_sconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrello',
            name='carrello_sconto',
        ),
        migrations.RemoveField(
            model_name='carrello',
            name='carrello_spese_spedizione',
        ),
        migrations.RemoveField(
            model_name='carrello',
            name='totale_carrello',
        ),
    ]
