# Generated by Django 5.1.7 on 2025-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banner', 'Banner'), ('testo', 'Testo'), ('card', 'Card'), ('video', 'Video'), ('immagine', 'Immagine')], max_length=20)),
                ('contenuto', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='editor_uploads/')),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('z_index', models.IntegerField(default=1)),
            ],
        ),
    ]
