# Generated by Django 5.2 on 2025-05-06 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticoloBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('contenuto', models.TextField()),
                ('contenuto_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Larghezza contenuto (px)')),
                ('contenuto_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza contenuto (px)')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('img_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Larghezza immagine (px)')),
                ('img_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza immagine (px)')),
                ('immagine_sfondo', models.ImageField(blank=True, null=True, upload_to='sfondi_blog/')),
                ('sfondo_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Larghezza sfondo (px)')),
                ('sfondo_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza sfondo (px)')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_blog/')),
                ('video_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Larghezza video (px)')),
                ('video_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza video (px)')),
                ('contorno_card', models.BooleanField(default=True, verbose_name='Contorno visibile')),
                ('slug', models.SlugField(unique=True)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='Scopri il nostro Blog', max_length=200)),
                ('sottotitolo', models.TextField(blank=True, default='Approfondimenti, novità e articoli scritti con passione.')),
                ('testo_bottone', models.CharField(default='Vai al Blog', max_length=100)),
                ('immagine_sfondo', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('altezza', models.PositiveIntegerField(default=300, help_text='Altezza del banner in pixel')),
                ('larghezza', models.PositiveIntegerField(default=1200, help_text='Larghezza del banner in pixel')),
                ('visibile', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(max_length=250)),
                ('data_pubblicazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('emoji', models.CharField(choices=[('👍', 'Like'), ('😊', 'Sorriso'), ('😮', 'Wow'), ('😢', 'Triste')], default='👍', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='blog.articoloblog')),
                ('risposta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='blog.commentoblog')),
                ('utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoSuggerito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField(default='')),
                ('link', models.URLField(blank=True, help_text='Inserisci il link al prodotto sul sito', null=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='correlati/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_correlati/')),
                ('img_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Larghezza immagine (px)')),
                ('img_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza immagine (px)')),
                ('video_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Larghezza video (px)')),
                ('video_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza video (px)')),
                ('data_pubblicazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articoloblog',
            name='prodotti_correlati',
            field=models.ManyToManyField(blank=True, related_name='articoli_correlati', to='blog.prodottosuggerito'),
        ),
    ]
