# Generated by Django 5.2 on 2025-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinformativo',
            name='colore_bottone',
            field=models.CharField(blank=True, default='#007bff', help_text='Colore del bottone in formato HEX (es. #ff0000)', max_length=7),
        ),
        migrations.AddField(
            model_name='bannerinformativo',
            name='font_color',
            field=models.CharField(blank=True, default='#000000', help_text='Colore del testo in formato HEX (es. #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='bannerinformativo',
            name='font_titolo',
            field=models.CharField(blank=True, default='Arial', help_text='Font per il titolo', max_length=100),
        ),
    ]
