# Generated by Django 5.1.7 on 2025-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessaggioContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('oggetto', models.CharField(max_length=255)),
                ('messaggio', models.TextField()),
                ('letto', models.BooleanField(default=False)),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
