# Generated by Django 5.1.7 on 2025-04-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessaggioContatto',
        ),
    ]
