# Generated by Django 5.1.7 on 2025-04-17 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amministratore', '0002_delete_messaggiocontatto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrataMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_arrivo', models.CharField(editable=False, max_length=6, unique=True)),
                ('codice_magazzino', models.CharField(max_length=50)),
                ('codice_prodotto', models.CharField(max_length=50)),
                ('nome_prodotto', models.CharField(max_length=100)),
                ('nome_fornitore', models.CharField(max_length=50)),
                ('cognome_fornitore', models.CharField(max_length=50)),
                ('p_iva', models.CharField(max_length=11)),
                ('nome_societa', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('data_arrivo', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
