# Generated by Django 5.1.7 on 2025-04-17 22:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entratamagazzino',
            name='codice_ordine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='entratamagazzino',
            name='prezzo_con_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='entratamagazzino',
            name='prezzo_totale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='entratamagazzino',
            name='prezzo_trasporto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='entratamagazzino',
            name='quantita',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
