# Generated by Django 5.1.7 on 2025-04-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0004_entratamagazzino_codice_ordine_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entratamagazzino',
            table='amministratore_entratamagazzino',
        ),
    ]
