# Generated by Django 5.2 on 2025-04-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0005_alter_entratamagazzino_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scalapay_secret_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
