# Generated by Django 5.2 on 2025-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0006_paymentsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='paypal_business_email',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paypal_mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paypal_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
