# Generated by Django 5.2 on 2025-04-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0007_remove_paymentsettings_paypal_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='paypal_business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
