# Generated by Django 5.2 on 2025-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0008_paymentsettings_paypal_business_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
