# Generated by Django 5.2 on 2025-05-01 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0009_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObiettivoMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.DateField(default=django.utils.timezone.now)),
                ('vendite', models.PositiveIntegerField(default=0)),
                ('ordini', models.PositiveIntegerField(default=0)),
                ('clienti', models.PositiveIntegerField(default=0)),
                ('prodotti', models.PositiveIntegerField(default=0)),
                ('valore_vendite', models.FloatField(default=0)),
                ('conversione', models.FloatField(default=0)),
                ('abbandoni', models.PositiveIntegerField(default=0)),
                ('valore_medio', models.FloatField(default=0)),
                ('prodotto_top', models.PositiveIntegerField(default=0)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
