# Generated by Django 5.2 on 2025-05-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0010_obiettivomensile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObiettivoMensile',
        ),
    ]
