# Generated by Django 5.2 on 2025-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0012_obiettivomensile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name': 'Impostazione Pagamento', 'verbose_name_plural': 'Impostazioni Pagamento'},
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Email Host'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password SMTP'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email mittente'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Porta'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Usa TLS'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='paypal_business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Business PayPal'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Client ID'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='paypal_mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=50, verbose_name='Modalità PayPal'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='paypal_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Secret Key'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='scalapay_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Scalapay Secret Key'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Public Key'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Secret Key'),
        ),
    ]
