# Generated by Django 5.2 on 2025-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0013_alter_paymentsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entratamagazzino',
            name='link_fornitore',
            field=models.URLField(blank=True, help_text='Inserisci un link al fornitore o alla fattura (facoltativo).', max_length=255, null=True),
        ),
    ]
