# Generated by Django 5.2 on 2025-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0014_entratamagazzino_link_fornitore'),
    ]

    operations = [
        migrations.AddField(
            model_name='entratamagazzino',
            name='aggiunto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entratamagazzino',
            name='codice_magazzino',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entratamagazzino',
            name='nome_prodotto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
