# Generated by Django 5.2 on 2025-05-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0015_entratamagazzino_aggiunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entratamagazzino',
            name='aggiunto',
        ),
    ]
