# Generated by Django 5.2 on 2025-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministratore', '0016_remove_entratamagazzino_aggiunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entratamagazzino',
            name='aggiunto',
            field=models.BooleanField(default=False, help_text='Indicazione manuale, non aggiorna automaticamente il prodotto.', null=True),
        ),
    ]
